version: '3'
services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/data/postgres

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: always
    ports:
      - 8001:8000
    env_file: .env
    command: 'sh -c "cp .pre-commit-config.yaml .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  db-data:
